# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "IOS Builder"
  lane :build do
    #cocoapods(
    #  clean_install: true,
    #)
    xcbuild(
      project: "./testcicd.xcodeproj",
      scheme:"testcicd",
      clean: true,
      derived_data_path: "./build/",
      destination: "platform=iOS Simulator,name=iPhone 14,OS=16.2",
      codesigning_identity: "",
      skip_codesigning: true,
    )
  end
  lane :test do
    scan(
      scheme: "testcicd",
      code_coverage: true,
      clean: true,
      project: "./testcicd.xcodeproj",
      derived_data_path: "./testOutput/",
      skip_build: true)
  end
   lane :coverage do
    slather(
      build_directory: "./testOutput/",
      scheme: "testcicd",
      proj: "./testcicd.xcodeproj",
      output_directory: "./testOutput/slatherOutput",
      cobertura_xml: false,
      html: true,
      ignore: ["Pods/*", "ThirdParty/*", "Frameworks/*"]) 
  end
end
