name: 'Astrapay PR Build'
on:
  pull_request:
    types:
      - opened
    branches:
      - 'main'

permissions:
  contents: read
  pull-requests: read

jobs:
  build-test-coverage:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Setup Ruby, JRuby and TruffleRuby
        uses: ruby/setup-ruby@v1.138.0
        with:
          ruby-version: '3.2.1' # Not needed with a .ruby-version file
          bundler-cache: true
      - name: Ruby Bundle Install
        run: bundle install
      - name: Build
        run: bundle exec fastlane build
      - name: Test
        run: bundle exec fastlane test
      - name: Coverage
        run: bundle exec fastlane coverage