name: 'Astrapay PR Build'
on:
  pull_request:
    types:
      - opened
    branches:
      - 'main'

permissions:
  contents: read
  pull-requests: read

jobs:
  build-test-coverage:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Build
        uses: fastlane build
      - name: Test
        uses: fastlane test
      - name: Coverage
        uses: fastlane coverage