name: 'Astrapay PR Build'
on:
  push:
    branches:
      - 'daily/**'
  pull_request:
    types:
      - opened
    branches:
      - 'main'

permissions:
  contents: read
  pull-requests: read

jobs:
  build-test-coverage:
    runs-on: ['macos-latest', 'ubuntu-latest']
    steps:
      - name: 'Checkout'
        uses: actions/checkout@main
      - name: 'Setup and Install Ruby'
        uses: ruby/setup-ruby@v1.138.0
        with:
          ruby-version: '3.2.1' # Not needed with a .ruby-version file
          bundler-cache: true
      - name: 'Build'
        run: bundle exec fastlane build
      - name: 'Test'
        run: bundle exec fastlane test
      - name: 'Coverage'
        run: bundle exec fastlane coverage
  depedency-check:
    runs-on: ['macos-latest', 'ubuntu-latest']
    steps:
      - name: 'Checkout'
        uses: actions/checkout@main
      - name: Depcheck
        uses: dependency-check/Dependency-Check_Action@main
        id: Depcheck
        with:
          project: 'test'
          path: '.'
          format: 'HTML'
          out: 'reports' # this is the default, no need to specify unless you wish to override it
          args: >
            --failOnCVSS 6
            --enableRetired
      - name: Upload Test results
        uses: actions/upload-artifact@master
        with:
           name: Depcheck report
           path: ${{github.workspace}}/reports
  